"""empty message

Revision ID: 6b2f9ab5038b
Revises: 
Create Date: 2020-12-20 14:42:37.082749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2f9ab5038b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('code', sa.String(length=256), nullable=True),
    sa.Column('icons', sa.String(length=256), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['db_organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_organization_create_time'), 'db_organization', ['create_time'], unique=False)
    op.create_index(op.f('ix_db_organization_update_time'), 'db_organization', ['update_time'], unique=False)
    op.create_table('db_resource_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_resource_type_create_time'), 'db_resource_type', ['create_time'], unique=False)
    op.create_index(op.f('ix_db_resource_type_update_time'), 'db_resource_type', ['update_time'], unique=False)
    op.create_table('db_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_role_create_time'), 'db_role', ['create_time'], unique=False)
    op.create_index(op.f('ix_db_role_update_time'), 'db_role', ['update_time'], unique=False)
    op.create_table('db_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('employ_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_user_create_time'), 'db_user', ['create_time'], unique=False)
    op.create_index(op.f('ix_db_user_name'), 'db_user', ['name'], unique=True)
    op.create_index(op.f('ix_db_user_update_time'), 'db_user', ['update_time'], unique=False)
    op.create_table('db_resource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('icons', sa.String(length=256), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('resource_type_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['db_resource.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['db_resource_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_resource_create_time'), 'db_resource', ['create_time'], unique=False)
    op.create_index(op.f('ix_db_resource_update_time'), 'db_resource', ['update_time'], unique=False)
    op.create_table('db_role_resource',
    sa.Column('role_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['db_role.id'], )
    )
    op.create_table('db_user_organization',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['db_organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], )
    )
    op.create_table('db_user_role',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['db_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], )
    )
    op.create_table('db_organization_resource',
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['db_organization.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['db_resource.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_organization_resource')
    op.drop_table('db_user_role')
    op.drop_table('db_user_organization')
    op.drop_table('db_role_resource')
    op.drop_index(op.f('ix_db_resource_update_time'), table_name='db_resource')
    op.drop_index(op.f('ix_db_resource_create_time'), table_name='db_resource')
    op.drop_table('db_resource')
    op.drop_index(op.f('ix_db_user_update_time'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_name'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_create_time'), table_name='db_user')
    op.drop_table('db_user')
    op.drop_index(op.f('ix_db_role_update_time'), table_name='db_role')
    op.drop_index(op.f('ix_db_role_create_time'), table_name='db_role')
    op.drop_table('db_role')
    op.drop_index(op.f('ix_db_resource_type_update_time'), table_name='db_resource_type')
    op.drop_index(op.f('ix_db_resource_type_create_time'), table_name='db_resource_type')
    op.drop_table('db_resource_type')
    op.drop_index(op.f('ix_db_organization_update_time'), table_name='db_organization')
    op.drop_index(op.f('ix_db_organization_create_time'), table_name='db_organization')
    op.drop_table('db_organization')
    # ### end Alembic commands ###
